import * as S from "./table.style";

const Canvas = () => {
  return(
    <S.Table>
      <S.TableCaption>DMS 2.0 / 02.09.2022-31.12.2022</S.TableCaption>
      <S.TableHead>
        <S.TableHeadRow>
          <S.TableHeadName rowSpan={2}>Work item</S.TableHeadName>
          <S.TableHeadMonth colSpan={7}>01 Sep - 07 Sep</S.TableHeadMonth>
          <S.TableHeadMonth colSpan={7}>08 Sep - 14 Sep</S.TableHeadMonth>
          <S.TableHeadMonth colSpan={7}>15 Sep - 21 Sep</S.TableHeadMonth>
          <S.TableHeadMonth></S.TableHeadMonth>
        </S.TableHeadRow>
        <S.TableHeadRow>
          <S.TableHeadSub>1</S.TableHeadSub>
          <S.TableHeadSub>2</S.TableHeadSub>
          <S.TableHeadSub>3</S.TableHeadSub>
          <S.TableHeadSub>4</S.TableHeadSub>
          <S.TableHeadSub>5</S.TableHeadSub>
          <S.TableHeadSub>6</S.TableHeadSub>
          <S.TableHeadSub>7</S.TableHeadSub>
          <S.TableHeadSub>1</S.TableHeadSub>
          <S.TableHeadSub>2</S.TableHeadSub>
          <S.TableHeadSub>3</S.TableHeadSub>
          <S.TableHeadSub>4</S.TableHeadSub>
          <S.TableHeadSub>5</S.TableHeadSub>
          <S.TableHeadSub>6</S.TableHeadSub>
          <S.TableHeadSub>7</S.TableHeadSub>
          <S.TableHeadSub>1</S.TableHeadSub>
          <S.TableHeadSub>2</S.TableHeadSub>
          <S.TableHeadSub>3</S.TableHeadSub>
          <S.TableHeadSub>4</S.TableHeadSub>
          <S.TableHeadSub>5</S.TableHeadSub>
          <S.TableHeadSub>6</S.TableHeadSub>
          <S.TableHeadSub>7</S.TableHeadSub>
          <S.TableHeadSub>7</S.TableHeadSub>
        </S.TableHeadRow>
      </S.TableHead>
      <S.TableBody>
        <S.TableRow>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
        </S.TableRow>
        <S.TableRowLevelOne>
          <S.TableData>
            <S.TableDataButton fold />
            <S.TableDataTaskCounter>1</S.TableDataTaskCounter>
            Marketing launch
          </S.TableData>
          <S.TableData $activeFrame={'Marketing launch'} colSpan={8}><div></div></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
        </S.TableRowLevelOne>
        <S.TableRowLevelTwo>
          <S.TableData>
            <S.TableDataButton fold />
            <S.TableDataTaskCounter>1</S.TableDataTaskCounter>
            Banners for social networks
          </S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
        </S.TableRowLevelTwo>
        <S.TableRowLevelThree>
          <S.TableData>
            <S.TableDataButton fold />
            <S.TableDataTaskCounter>1</S.TableDataTaskCounter>
            Banners for social networks
            </S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
        </S.TableRowLevelThree>
        <S.TableRowLevelFour>
          <S.TableData>
            <S.TableDataButton fold />
            <S.TableDataTaskCounter>2</S.TableDataTaskCounter>
            Choosing a platform for ads
          </S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
        </S.TableRowLevelFour>
        <S.TableRowLevelFive>
          <S.TableData>
            <S.TableDataTaskCounter>0</S.TableDataTaskCounter>
            Banners for social networks
            </S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
        </S.TableRowLevelFive>
        <S.TableRowLevelFive>
          <S.TableData>
            <S.TableDataTaskCounter>0</S.TableDataTaskCounter>
            Banners for social networks
            </S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
        </S.TableRowLevelFive>
        <S.TableLastRow>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
          <S.TableData></S.TableData>
        </S.TableLastRow>
      </S.TableBody>
    </S.Table>
  )
}

export default Canvas;
